version: "3.8"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gasselin/data/mysql

  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gasselin/data/html

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    ports:
      - "443:443"
    restart: unless-stopped