version: "3.8"

networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gasselin/data/mysql

  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gasselin/data/html

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    restart: always