FLUSH PRIVILEGES;
ALTER USER root@localhost IDENTIFIED BY '$DB_PWD';
CREATE DATABASE $DB_NAME;
CREATE USER IF NOT EXISTS '$DB_USR'@'%' IDENTIFIED BY '$DB_PWD';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USR'@'%' IDENTIFIED BY '$DB_PWD';
FLUSH PRIVILEGES;
EXIT;