CREATE DATABASE $DB_NAME;
ALTER USER root@localhost IDENTIFIED BY $DB_PWD;
CREATE USER IF NOT EXISTS $DB_USR@localhost IDENTIFIED BY $DB_PWD;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USR@localhost;
FLUSH PRIVILEGES;
EXIT;